name: CS
on: [ push, pull_request ]
jobs:
  coding-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@2.23.0
        with:
          php-version: 8.1
          coverage: pcov
          tools: cs2pr

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/composer
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Code style with phpcs
        run: make cs
